### ISSUE TITLE
"with" capitalization

### ISSUE THREAD

**Issue by ehfeng** [samsouder/titlecase#6]
In the case "Better with Friends", "with" shouldn't be capitalized, but I'm seeing titlecase capitalize it.

**Comment by samsouder** [comment]
I chose specifically not to include `with` in the small words definition as John Gruber didn't and that's where I based my spec: https://daringfireball.net/projects/titlecase/examples-edge-cases

**Comment by ehfeng** [comment]
Fair. Thanks for fast reply.
